---
title: "Exploratory Data Analysis"
author: "Karen Jiang"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(usmap)
library(wesanderson)
library(ggrepel)

options(scipen = 999)
```

```{r}
aco <- readRDS("clean_data/aco.RDS")
aco_long <- readRDS("clean_data/aco_long.RDS")
county <- readRDS("clean_data/county.RDS")
```

```{r}

d <- county %>%
  filter(Beneficiary == "End Stage Renal Disease") %>%
  filter(Category == "Person Years")

plot_usmap(data = d,
           regions = "counties", 
           values = "Values",
           color = "white",
           size = 0.1) +
  scale_fill_continuous(low = "#DFF0EA", high = "#2A7886") +
    theme(legend.position = "bottom",
          legend.direction = "horizontal") + 
  labs(
    fill = "Test"
  )
```

```{r}

plot_usmap(data = d,
           regions = "counties", 
           include = "California",
           values = "Values",
           color = "white") +
  scale_fill_continuous(low = "#DFF0EA", high = "#2A7886") +
    theme(legend.position = "bottom",
          legend.direction = "horizontal") + 
  labs(
    fill = "Test"
  )


```

Number of Beneficiaries against Number of Providers

```{r}
ggplot(aco, aes(x = N_AB, y = N_total_providers)) + geom_point(aes(color = current, size = num_states), alpha = 0.5) +
  scale_x_log10() +
  scale_y_log10() + 
  theme_classic() +
  labs(
    x = "Number of Assigned Beneficiaries \n(Log 10)",
    y = "Number of Total Providers \n(Log 10)"
  )

```
```{r}
aco %>% 
  ggplot(aes(x=ratio_AB_to_providers)) +
  geom_density(aes(fill = current), alpha = 0.4)

```



```{r}
aco %>%
  ggplot(aes(x=ratio_AB_to_providers)) +
  geom_density(aes(fill = GenSaveLoss_categorical), alpha = 0.4)
```



```{r}
aco_long %>%
  filter(Category == "Age (%)") %>%
  ggplot(aes(x = Values, y = BnchmkMinExp)) +
  geom_point(aes(color = GenSaveLoss_categorical), alpha = 0.2) +
  geom_hline(yintercept = 0) +
  facet_grid(rows = 1, facets = ~ Names) +
  theme_classic() +
  xlim(0,1) + 
  labs(
    x = "Percent of Beneficiaries in Age category",
    y = "Benchmark minus Expenditures",
    color = "Generated: "
  ) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    panel.spacing.x = unit(2, "line")
  )
```
```{r}
aco_long %>%
  filter(Category == "Provider (%)") %>%
  ggplot(aes(x = Values)) +
  geom_density(aes(fill = GenSaveLoss_categorical), alpha = 0.4) +
  facet_grid(rows = vars(Names)) +
  theme_classic()
```




