---
title: "Extract Transform Load - Beneficiaries"
author: "Karen Jiang"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidycensus)
library(readr)
library(readxl)
library(gt)
library(usmap)
```

## Exploratory Data Analysis - Part 2

* ACO general information
* **Beneficiaries information by ACO**
* Fee-for-Service Expenditures by ACO

To better understand how MSSP scoring and classifications for ACOs, information can be found in the  [MSSP Shared Savings and Losses Assignement and Methodology ]("https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/sharedsavingsprogram/Downloads/Shared-Savings-Losses-Assignment-Spec-V7.pdf").

```{r read_data}

# Beneficiaries

beneficiaries <- 
  read_csv("data/2018_Number_of_ACO_Assigned_Beneficiaries_by_County_PUF.csv")

beneficiaries_dictionary <-
  read_excel("data-dictionary/Dictionary.ACO.SSP.COUNTY.ASSIGNED.PUF.2018.xlsx",
             sheet = "Data Dictionary",
             col_names = TRUE)

beneficiaries_dictionary

# Fee for Service

ffs <- 
  read_csv("data/2018_County-level_FFS_Data_for_Shared_Savings_Program_Benchmark_PUF.csv")

ffs_dictionary <-
  read_excel("data-dictionary/Dictionary.ACO.SSP.COUNTYRATE.PUF.PY19.2018.xlsx",
             sheet = "Data Dictionary",
             col_names = TRUE)

head(ffs_dictionary)
```

```{r functions}

find_definition_beneficiaries <- function(variable, col = c("short", "long", "type")) {
  col <- match.arg(col)
  beneficiaries_dictionary %>%
    filter(`Variable Name` == variable) %>%
    pull(
      switch(col,
         short = "Short Description",
         long = "Long Description",
         type = "Missing or Suppressed Values"))
}

#Example: 
find_definition_beneficiaries(Tot_AB, "type")

find_definition_ffs <- function(variable, col = c("short","long","type")) {
  col <- match.arg(col)
  ffs_dictionary %>%
    filter(`Variable Name` == variable) %>%
    pull(
      switch(col,
             short = "Short Description",
             long = "Long Description",
             type = "Missing or Suppressed Values"))
}

# Example: 
# find_definition_ffs("County_ID", "long")
```


### Understanding the Beneficiaries dataset

```{r}


plot_usmap(data = beneficiaries, regions = "counties")
```

